### ISSUE TITLE
Unable to add multiple variations to cart.

### ISSUE THREAD

**Issue by vegaix9** [Phiph/woocommerce-fixed-quantity#1]
Only 1 variation can be added to the cart at a time. Any additional variation added to the cart will receive confirmation, but does not appear.

**Comment by vegaix9** [comment]
@Phiph Hi Phiph, has there been any progress on this bug or a possible work around?

**Comment by Phiph** [comment]
Hi @vegaix9 Sorry i've been really caught up with work, I'll try and have a look at it in the coming weeks.

**Comment by Phiph** [comment]
Hi @vegaix9 There will be a fix for this by tuesday!

**Comment by Phiph** [comment]
@vegaix9 I've added a fix in the latest master :)
