### ISSUE TITLE
WooCommerce 3.2.x Support

### ISSUE THREAD

**Issue by AechDub** [Phiph/woocommerce-fixed-quantity#3]
Any plans to add support here?

**Comment by Phiph** [comment]
Hey @hutchwhite I made this  awhile ago as a fork to support variable products.

It seems that there is a bit of interest :) I'll spend some time next week maintaining this repo. Cheers

**Comment by AechDub** [comment]
Any chance you'll get some time for this?

**Comment by Phiph** [comment]
@hutchwhite I've been working on it today! It's been a while since I looked at this plugin! Gimme a few more days and hopefully i'll have a patch up soon!.

**Comment by AechDub** [comment]
Awesome.  Thanks!

**Comment by Phiph** [comment]
Hey @hutchwhite 

I'm working on rethinking how this works at the moment, As its a fork from another repo I'm trying to figure out if its worth in the long run to turn this into some sort of addon for his tool.

so i can try and gear the development of this a bit more, 

How're you thinking of using this plugin?
Are there any features you'd want to see?

**Comment by AechDub** [comment]
The big thing I need is to do pricing of specific quantities on variable products.  

Example: I have a variable product with attributes.  I want to have fixed quantities of 3, 6, 12, 24.  I want to set price points on those quantities like 3 = 12 each; 6 = 11 each; 12 = 9 each; 24 = 7 each.

**Comment by Phiph** [comment]
Thanks, in the current way the plugin works, you set the discount at the product level, rather than the individual variation. Would this still work in your case?

**Comment by Phiph** [comment]
Hi @hutchwhite,

It should work fine now with the latest release :)
